### PR TITLE
Add zero option to ExtraVectorsFlags to allow blender plugin to set the

### PR DESCRIPTION
**Pull request by Ghostwalker71**
value during export.

### CODE REVIEW

**Comment by neomonkeus** [comment]
@ttl269 - can you review.

**Comment by Ghostwalker71** [comment]
This change works out of the box with nifskope 1.2.0 alpha 2, no need to version bump

**Comment by neomonkeus** [comment]
Updating the version should be general practice. 
Features which potentially break compatibility with tools should have either the minor/major component increased depending on the content. This only needs an update to the revision number.

**Comment by Ghostwalker71** [comment]
I had missed your response about incrementing the version number, It's ready to go now.

**Pull request merged**
